---
title: "Epistemic States and Statistical Normality in Causal Judgments"
author: "Lara Kirfel & David Lagnado"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")
```

# Install packages

```{r, message=FALSE}
install.packages("pastecs");
install.packages("reshape")
install.packages("lubridate")
install.packages("lsr")
install.packages("janitor")
install.packages("DT")
install.packages("Hmisc")
install.packages("broom")
install.packages("tidyverse")
install.packages("ez")
install.packages("schoRsch")
install.packages("stringr")
```

# Load packages 

```{r, message=FALSE}
library("pastecs")
library("reshape")
library("knitr")
library("lubridate")
library("lsr")
library("janitor") # for cleaning variable names 
library("DT") # for nice tables
library("Hmisc") # for smean function for bootstrapped confidence intervals 
library("broom") # for tidy regression results
library("tidyverse") # for data wrangling, visualization, etc. 
library("ez")
library("schoRsch")
library("lme4")
library("stringr")
library("dplyr")
library("nlme")
library("afex")

```

```{r}
# set ggplot theme 
theme_set(
  theme_classic()
)
```

# Experiment 1:

## Read in Data

```{r}
df.data = read.csv(file = "EpStates_2.csv", stringsAsFactors = F, sep = ",") %>% 
  filter(row_number() > 2) %>% # additional rows in qualtrics csv
  clean_names() %>% 
  filter(distribution_channel != "preview",
         !condition =="", #exclude bot fails,
          progress ==100| progress==99)
 
```

## Structure and edit data

```{r}

df.exp = df.data %>% 
  mutate(participant = 1:n()) %>% 
  rename(duration=duration_in_seconds) %>% 
  mutate(duration=as.numeric(duration)) %>% 
  select(h_check_fact_1:b_b_2_1,
         participant,
         order,
         duration,
         condition,
         gender,
         age) %>% 
  gather("index", "value", -c(age, gender, participant, condition, duration, order))%>% 
  filter(value != "") %>%
  arrange(index)%>%
  mutate(index = ifelse(str_detect(index,"_c_1"),
                        "cause_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_c_2"),
                        "cause_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_cf_1"),
                        "cf_externally_caused",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_cf_2"),
                        "cf_self_caused",
                        index)) %>% 
  mutate(index = ifelse(str_detect(index,"_k_1"),
                        "could_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_k_2"),
                        "could_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_b_1"),
                        "blame_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_b_2"),
                        "blame_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"fact_1"),
                        "fact_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"fact_2"),
                        "fact_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"know_1"),
                        "know_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"know_2"),
                        "know_2",
                        index)) %>% 
  mutate(index = ifelse(str_detect(index,"mail_1"),
                        "mail_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"mail_2"),
                        "mail_2",
                        index)) %>%
  mutate(index = ifelse(str_detect(index,"read_1"),
                        "read_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"read_2"),
                        "read_2",
                        index)) %>%
  mutate(order = ifelse(order == 1,"dont know first", 
                          ifelse(order == 2, "know first", " ")))%>%
  mutate(scenario = ifelse(condition == 1,"hospital", 
                          ifelse(condition == 2, "garden", 
                          ifelse(condition == 3, "bakery", " "))))%>%
  spread(index, value) %>%
  arrange(participant)

```


```{r}
####Experiment 1: Create filter
df.exp<- df.exp%>%  
  mutate(check_total=if_else(know_1=="2", 1, 0)) %>% 
  mutate(check_total=if_else(know_2 =="2", check_total+1, check_total)) %>% 
  mutate(check_total=if_else(fact_1 =="1", check_total+1, check_total)) %>% 
  mutate(check_total=if_else(fact_2=="1",  check_total+1, check_total)) %>% 
  mutate(check_total=if_else(read_1=="1",  check_total+1, check_total)) %>% 
  mutate(check_total=if_else(read_2=="2",  check_total+1, check_total)) %>% 
  mutate(check_total=if_else(mail_1=="1",  check_total+1, check_total)) %>% 
  mutate(check_total=if_else(mail_2=="1",  check_total+1, check_total))

#### Set filter
df.exp<-df.exp %>% 
  filter(check_total ==8) ####Set to 4 to change exlusion criterion to "all check questions correct"
```



```{r}

df.exp_cf = df.exp %>% 
  select(participant,
         condition,
         contains("cf"))%>% 
  gather("index", "value", -c(participant, condition))%>% 
  filter(value != "") %>%
  arrange(index)%>%
  mutate(scenario = ifelse(condition == 1,"hospital", 
                          ifelse(condition == 2, "garden", 
                          ifelse(condition == 3, "bakery", " "))))%>%
  spread(index, value) %>%
  arrange(participant)

write.csv(df.exp_cf,'Counterfactuals.csv')
```

##join with counterfactual responses

```{r}
df.counterfactuals<-read.csv("Counterfactuals_analysed.csv") %>% 
  select(participant, code_1, detailed_1, code_2, detailed_2) 
  
df.exp<-df.exp %>% 
inner_join(df.counterfactuals, by="participant") %>% 
filter(code_1 != "0")

```

### Demographics
```{r}
####Experiment 2
###Demographics

df.exp_demo <- df.exp %>% 
  select(age, gender, duration) %>% 
  mutate(age=as.numeric(age)) %>%
  transform(gender= ifelse(gender==1, "Male", #recode numbers into gender categories
                    ifelse(gender==2, "Female",
                    ifelse(gender==3, "Prefer not to say", gender)))) %>% 
  filter(age<100 |age ==" ") %>% #remove outliers (year) or N.A.s
  summarize(n=n(),
             female=sum(gender=="Female"),
             not_say=sum(gender=="Prefer not to say"),
             mean_age = mean(age),
             std_age=sd(age),
             mean_time=mean(duration/60),
             sd_time=sd(duration/60)
            )
```


```{r}

#### counterfacual responses: fine grained categories

df.exp_long = df.exp %>% 
  select(scenario,
         order,
         participant,
         contains("cause"),
         contains("could"),
         contains("blame"),
         contains("code"),
         contains("detailed"),
         -starts_with("cf"))%>%
  gather(condition, rating, "cause_1":"detailed_2") %>%  
  mutate(ignorance = ifelse(str_detect(condition, "1"),
                        "externally caused", "self-caused")) %>% 
  mutate(condition = ifelse(str_detect(condition, "cause"),"causal_rating", 
                                ifelse(str_detect(condition, "could"), "know_rating", 
                                       ifelse(str_detect(condition, "blame"), "blame_rating",
                                              ifelse(str_detect(condition, "code"), "counterfactual",
                                                     "counterfactual_specific"))))) %>% 
  spread(condition, rating) %>% 
  mutate(scenario=as.factor(scenario)) %>% 
  mutate(ignorance=as.factor(ignorance)) %>% 
  mutate(causal_rating=as.numeric(causal_rating)) %>% 
  mutate(know_rating=as.numeric(know_rating)) %>% 
  mutate(blame_rating=as.numeric(blame_rating)) %>% 
  mutate(counterfactual=recode(counterfactual, 
                               '1' = "undoing causal action",
                               '2_1' = "direct epistemic change",
                               '2_2' = "by e-mail reading", 
                               '2_3' = "e-mail made available",
                               '2_4' = "by someone else",
                               '2_5' = "by additional action of agent",
                               '2_6' = "epistemic state change about technical default",
                               '2_7' = "by reading deleted e-mail",
                               '4' =  "environment"))
  
```


```{r}

#### counterfacual responses: split according to experimental or other category
df.exp_long = df.exp %>% 
  select(scenario,
         order,
         participant,
         contains("cause"),
         contains("could"),
         contains("blame"),
         contains("code"),
         contains("detailed"),
         -starts_with("cf"))%>%
  gather(condition, rating, "cause_1":"detailed_2") %>%  
  mutate(ignorance = ifelse(str_detect(condition, "1"),
                        "externally caused", "self-caused")) %>% 
  mutate(condition = ifelse(str_detect(condition, "cause"),"causal_rating", 
                                ifelse(str_detect(condition, "could"), "know_rating", 
                                       ifelse(str_detect(condition, "blame"), "blame_rating",
                                              ifelse(str_detect(condition, "code"), "counterfactual",
                                                     "counterfactual_specific"))))) %>% 
  spread(condition, rating) %>% 
  mutate(scenario=as.factor(scenario)) %>% 
  mutate(ignorance=as.factor(ignorance)) %>% 
  mutate(causal_rating=as.numeric(causal_rating)) %>% 
  mutate(know_rating=as.numeric(know_rating)) %>% 
  mutate(blame_rating=as.numeric(blame_rating)) %>% 
  mutate(counterfactual=recode(counterfactual, 
                               '1' = "undoing causal action",
                               '2_1' = "direct epistemic change",
                               '2_2' = "by e-mail reading", 
                               '2_3' = "e-mail made available",
                               '2_4' = "by someone else",
                               '2_5' = "by additional action of agent",
                               '2_6' = "epistemic state change about technical default",
                               '2_7' = "by reading deleted e-mail",
                               '4' =  "environment"))
  
```


```{r}
####final with counterfacual responses: fewer categories

df.exp_long = df.exp %>% 
  select(scenario,
         order,
         participant,
         contains("cause"),
         contains("could"),
         contains("blame"),
         contains("code"),
         contains("detailed"),
         -starts_with("cf"))%>%
  gather(condition, rating, "cause_1":"detailed_2") %>%  
  mutate(ignorance = ifelse(str_detect(condition, "1"),
                        "externally caused", "self-caused")) %>% 
  mutate(condition = ifelse(str_detect(condition, "cause"),"causal_rating", 
                                ifelse(str_detect(condition, "could"), "know_rating", 
                                       ifelse(str_detect(condition, "blame"), "blame_rating",
                                              ifelse(str_detect(condition, "code"), "counterfactual",
                                                     "counterfactual_specific"))))) %>% 
  spread(condition, rating) %>% 
  mutate(scenario=as.factor(scenario)) %>% 
  mutate(ignorance=as.factor(ignorance)) %>% 
  mutate(causal_rating=as.numeric(causal_rating)) %>% 
  mutate(know_rating=as.numeric(know_rating)) %>% 
  mutate(blame_rating=as.numeric(blame_rating)) %>% 
  mutate(counterfactual=recode(counterfactual, 
                               '1' = "causal action",
                               '2_1' = "epistemic change",
                               '2_2' = "... self-caused", 
                               '2_3' = "... externally caused",
                               '2_4' = "... externally caused",
                               '2_5' = "... self-caused",
                               '2_6' = "epistemic change",
                               '4' =  "environment")) %>% 
  mutate(counterfactual=factor(counterfactual, levels=c("causal action", "epistemic change", "... self-caused", "... externally caused", "environment", "X")))
```

```{r}

### Dataframe just with CF Responses (non-sensical deleted)

df.exp_cf<- df.exp_long %>% 
  select(participant, scenario, order, ignorance, counterfactual) %>% 
  reshape(v.names="counterfactual", timevar="ignorance", idvar=c("participant", "scenario", "order"),
        direction="wide") %>% 
  filter(`counterfactual.externally caused` != "X" ) %>% ###delete those participants who selected a non-sensical answer
  reshape(idvar=c("participant", "scenario", "order"), 
        sep = ".", direction = "long") %>%  ###reshape back into long format
  remove_rownames() 

```


```{r}
df.exp_cf_desc <- df.exp_long %>% 
  group_by(counterfactual, ignorance) %>% 
  summarize(n=n()) %>% 
  mutate(freq=prop.table(n))

```


```{r}

### Experiment 2
#### Plot Cause  Rating
myTheme <-   theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 18, vjust=.9), 
                   axis.text.x = element_text(color="black", size = 18),
                   axis.text.y = element_text(color="black", size = 18), 
                   strip.text.x = element_text(color="black", size = 18),
                   legend.text = element_text(color="black", size = 18),
                   legend.position = "top",
                   legend.title = element_blank(),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"))
    

## Cause Rating

Fig2a <- ggplot(df.exp_long, aes(x=scenario, y=causal_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  geom_jitter(position = position_jitterdodge(jitter.height = 0.1, dodge.width = 0.8, jitter.width=0.2), alpha = 
  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  
  scale_fill_manual(values=c("#999999", "#E69F00"), name="blank")+
  labs( y="Causal Rating")+
  theme_bw()+
  myTheme

Fig2a
ggsave(Fig2a, file="Fig2a.pdf", dpi=400, height = 6, width = 8)



## Could have known Rating

Fig1b <- ggplot(df.exp_long, aes(x=scenario, y=know_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  #geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  geom_jitter(position = position_jitterdodge(jitter.height = 0.1, dodge.width = 0.8, jitter.width=0.2), alpha = 
  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  
    scale_fill_manual(values=c("#999999", "#E69F00"))+
  #scale_fill_brewer(palette="Dark2")+
  labs( y="Could have known Rating")+
  theme_bw()+
  myTheme

Fig1b
ggsave(Fig1b, file="Know.pdf", dpi=400, height = 5, width = 8)
ggsave(Fig1b, file="Know.jpeg", dpi=400, height = 5, width = 8)


## Blame Rating

Fig1c <- ggplot(df.exp_long, aes(x=scenario, y=blame_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  #geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  geom_jitter(position = position_jitterdodge(jitter.height = 0.1, dodge.width = 0.8, jitter.width=0.2), alpha = 
  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  
  #scale_fill_brewer(palette="Set1")+
  scale_fill_manual(values=c("#999999", "#E69F00"))+
  labs( y="Blame for Ignorance Rating")+
  theme_bw()+
  myTheme

Fig1c

ggsave(Fig1c, file="Blame.pdf", dpi=400, height = 5, width = 8)
ggsave(Fig1c, file="Blame.jpeg", dpi=400, height = 5, width = 8)


## Counterfactual Selection

Fig2b<- df.exp_cf %>%  
  ggplot(aes(x=counterfactual, group=ignorance))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of responses") +
  facet_wrap(~ignorance)+
  scale_fill_brewer(palette = "Greys")+
  theme_bw()+
  myTheme+
  theme(legend.position= "none")+
  theme(
  axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14))

plot(Fig2b)
ggsave(Fig2b, file="Fig2b.pdf", dpi=400, height = 5, width = 8)


```
####CogSci plot
```{r}


myTheme <-   theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 14), 
                   axis.text.x = element_text(color="black", size = 14),
                   axis.text.y = element_text(color="black", size = 14), 
                   strip.text.x = element_text(color="black", size = 14),
                   legend.text = element_text(color="black", size = 14),
                   legend.position = "top",
                   legend.title = element_blank(),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"))
    


library(cowplot)
library(dplyr)
library(readr)



# Load packages ----
library(ggplot2)

# Defining the geom_flat_violin function ----
# Note: the below code modifies the
# existing github page by removing a parenthesis in line 50

"%||%" <- function(a, b) {
  if (!is.null(a)) a else b
}

geom_flat_violin <- function(mapping = NULL, data = NULL, stat = "ydensity",
                             position = "dodge", trim = TRUE, scale = "area",
                             show.legend = NA, inherit.aes = TRUE, ...) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomFlatViolin,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      trim = trim,
      scale = scale,
      ...
    )
  )
}

#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomFlatViolin <-
  ggproto("GeomFlatViolin", Geom,
    setup_data = function(data, params) {
      data$width <- data$width %||%
        params$width %||% (resolution(data$x, FALSE) * 0.9)

      # ymin, ymax, xmin, and xmax define the bounding rectangle for each group
      data %>%
        group_by(group) %>%
        mutate(
          ymin = min(y),
          ymax = max(y),
          xmin = x,
          xmax = x + width / 2
        )
    },

    draw_group = function(data, panel_scales, coord) {
      # Find the points for the line to go all the way around
      data <- transform(data,
        xminv = x,
        xmaxv = x + violinwidth * (xmax - x)
      )

      # Make sure it's sorted properly to draw the outline
      newdata <- rbind(
        plyr::arrange(transform(data, x = xminv), y),
        plyr::arrange(transform(data, x = xmaxv), -y)
      )

      # Close the polygon: set first and last point the same
      # Needed for coord_polar and such
      newdata <- rbind(newdata, newdata[1, ])

      ggplot2:::ggname("geom_flat_violin", GeomPolygon$draw_panel(newdata, panel_scales, coord))
    },

    draw_key = draw_key_polygon,

    default_aes = aes(
      weight = 1, colour = "grey20", fill = "white", size = 0.5,
      alpha = NA, linetype = "solid"
    ),

    required_aes = c("x", "y")
  )


CausalExp2 <- ggplot(df.exp_long, aes(x=ignorance,y=causal_rating, fill = ignorance, colour = ignorance))+
  coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_flat_violin(position = position_nudge(x = .1, y = 0),adjust =1.5, alpha=0.5)+
  geom_point(position = position_jitter(width = .1), size = 1, alpha=0.5)+
  stat_summary(fun.data = mean_cl_normal, geom = "pointrange", position = position_nudge(x=.1), colour = "BLACK", width = 0.5,
  size = 1.2, shape = 21, fatten = 2.5)+
  ylab('Score')+xlab('Group')+
  theme_cowplot()+
  scale_fill_manual(values=c("#999999", "#E69F00"), name="blank", labels=c("Knowledge", "No Knowledge"))+
  scale_colour_manual(values=c("#999999", "#E69F00"), name="blank", labels=c("Knowledge", "No Knowledge"))+
  labs( y="Causal Rating")+
  theme_bw()+
  guides(fill = FALSE, colour = FALSE) +
  facet_grid(~scenario)+
  theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 12, vjust=.9), 
                   axis.text.x = element_text(color="black", size = 12),
                   axis.text.y = element_text(color="black", size = 12), 
                   strip.text.x = element_text(color="black", size = 12),
                   legend.text = element_text(color="black", size = 12),
                   legend.position = "top",
                   legend.title = element_blank(),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"))
    

CausalExp2
ggsave(CausalExp2, file="CausalExp2.jpeg", dpi=400, height = 3, width = 4)
ggsave(CausalExp2, file="CausalExp2.jpeg", dpi=400, height = 5, width = 8)


CFExp2<-ggplot(df.exp_cf, aes(x=counterfactual, group=ignorance))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("proportion of response") +
  facet_wrap(~ignorance)+
  scale_fill_brewer(palette="Greys",  direction=-1)+
  theme_bw()+
  myTheme+
  theme(legend.position= "none")+
  theme(axis.title.y = element_text(color="black", size = 14),
    axis.text.y = element_text(color="black", size = 12, margin = margin (r=0, l=0)),
    axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 12),
    strip.text.x = element_text(size = 12))

#margin = margin(t = 0, r = 20, b = 0, l = 0)

CFExp2
ggsave(CFExp2, file="CFExp2.jpeg", dpi=400, height = 4, width = 5)
```



```{r}
######Subgroup Analysis

myTheme <-   theme(plot.title=element_text(size=18, 
                                    face="bold", 
                                    hjust=0.5,
                                    lineheight=1.2),
                   axis.title.y = element_text(color="black", size = 18, vjust=.9),
                   axis.title.x = element_text(color="black", size = 18, vjust=.9), 
                   axis.text.x =  element_text(color="black", size = 16, vjust=.9),
                   axis.text.y = element_text(color="black", size = 18), 
                   strip.text.x = element_text(color="black", size = 16),
                   legend.text = element_text(color="black", size = 18),
                   legend.title = element_text(color="black", size = 18),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"))


####continue working here
df.text = df.exp_long%>% 
   filter(counterfactual=="... self-caused" | counterfactual=="... externally caused") %>% 
  count(counterfactual, ignorance) %>% 
  mutate(
         label = str_c("n = ", n))

Fig2b2 <- df.exp_long %>% 
  filter(counterfactual=="... self-caused" | counterfactual=="... externally caused") %>% 
  ggplot(aes(x=counterfactual, y=causal_rating, fill=counterfactual)) + 
  coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_jitter(height = 0.1, width = 0.1, alpha =  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) + 
  #geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  scale_fill_manual(values=c("gray71", "grey25"), name="blank")+
  facet_wrap(~ignorance)+
  #geom_text(data = df.text,
  #          label = label,
  #          size = 6) +
  labs(x= "Epistemic state change")+
  labs(y="Causal Rating")+
  labs(title="Ignorance")+
  theme_bw()+
  myTheme+
  theme(axis.text.x = element_text(angle = 15, hjust = 1, color="black", size = 14),
          legend.position= "none")



Fig2b2
ggsave(Fig2b2, file="Fig2b2.pdf", dpi=400, height = 5, width = 8)




####### Analysis
### Causal Ratings according to Countefactual Category

df.exp_long <- within(df.exp_long, ignorance <- relevel(ignorance, ref = 'self-caused'))
df.exp_long <- within(df.exp_long, scenario<- relevel(scenario, ref = 'bakery'))


df.exp_subgroup <- df.exp_long %>% 
   filter(counterfactual=="... self-caused" | counterfactual=="... externally caused")



C2  <- lmer(causal_rating ~ 1 + ignorance*counterfactual + (1 | participant),df.exp_subgroup, REML=T)
summary(C2)

t.test(causal_rating ~ counterfactual, data = df.exp_subgroup[df.exp_subgroup$ignorance=="externally caused",], paired = F)
t.test(causal_rating ~ counterfactual, data = df.exp_subgroup[df.exp_subgroup$ignorance=="self-caused",], paired = F)


df.exp_desc_subgroup<- df.exp_subgroup %>%
  group_by(ignorance, counterfactual) %>%
  summarise(c_mean = mean(causal_rating),#causal rating
            c_sd   = sd(causal_rating), 
            c_se   = c_sd / sqrt(n()), 
            c_upper_ci = c_mean+c_se*1.96, 
            c_lower_ci = c_mean-c_se*1.96
  )

```






```{r}
df.exp_desc_ratings<- df.exp_long%>%
  group_by(ignorance) %>%
  summarise(c_mean = mean(causal_rating),#causal rating
            c_sd   = sd(causal_rating), 
            c_se   = c_sd / sqrt(n()), 
            c_upper_ci = c_mean+c_se*1.96, 
            c_lower_ci = c_mean-c_se*1.96,
            k_mean = mean(know_rating),#could have known rating
            k_sd   = sd(know_rating), 
            k_se   = k_sd / sqrt(n()), 
            k_upper_ci = k_mean+c_se*1.96, 
            k_lower_ci = k_mean-c_se*1.96,
            b_mean = mean(blame_rating),#blame rating
            b_sd   = sd(blame_rating), 
            b_se   = b_sd / sqrt(n()), 
            b_upper_ci = b_mean+c_se*1.96, 
            b_lower_ci = b_mean-c_se*1.96
  )
```


```{r}
### Experiment 2: Causal Ratings

df.exp_long <- within(df.exp_long, ignorance <- relevel(ignorance, ref = 'self-caused'))
df.exp_long <- within(df.exp_long, scenario<- relevel(scenario, ref = 'bakery'))


mixed(causal_rating ~ 1 + ignorance*scenario +  (1 | participant), df.exp_long, method = 'LRT')
C2  <- lmer(causal_rating ~ 1 + ignorance*scenario + (1 | participant), df.exp_long, REML=T)
summary(C2)

```

```{r}

#### Counterfactual Responses

df.exp_cf <- within(df.exp_cf, ignorance <- relevel(ignorance, ref = 'self-caused'))



library(VGAM)
vglm2 <- vglm(counterfactual ~ ignorance*scenario, family=multinomial(refLevel="causal action"), df.exp_cf)
vglm1 <- vglm(counterfactual ~ ignorance, family=multinomial(refLevel="causal action"), df.exp_cf)
vglm0 <- vglm(counterfactual ~ +1, family=multinomial(refLevel="causal action"), df.exp_cf)


#coding
head(depvar(vglm1))

#number in categories
colSums(depvar(vglm1))

#likelihood ratio test null vs factor model 
VGAM::lrtest(vglm0, vglm1)

#summary null model
sum0 <- summary(vglm0)

#factor model
sum1   <- summary(vglm1)

coefMN <- coef(sum1)

##odds ratio
exp(coef(vglm1))


#lr test interaction with scenario
VGAM::lrtest(vglm1, vglm2)
sum2   <- summary(vglm2)


#R
LLf   <- logLik(vglm1)
LL0   <- logLik(vglm0)


as.vector(1 - (LLf / LL0))


```


```{r}
### Experiment 2: Knowledge Ratings

df.exp_long <- within(df.exp_long, ignorance <- relevel(ignorance, ref = 'self-caused'))
df.exp_long <- within(df.exp_long, scenario<- relevel(scenario, ref = 'bakery'))


mixed(know_rating ~ 1 + ignorance*scenario +  (1 | participant), df.exp_long, method = 'LRT')
K2  <- lmer(know_rating ~ 1 + ignorance*scenario + (1 | participant), df.exp_long, REML=T)
summary(K2)

```

```{r}
### Experiment 2: Blame Ratings

df.exp_long <- within(df.exp_long, ignorance <- relevel(ignorance, ref = 'self-caused'))
df.exp_long <- within(df.exp_long, scenario<- relevel(scenario, ref = 'bakery'))



mixed(blame_rating ~ 1 + ignorance*scenario +  (1 | participant), df.exp_long, method = 'LRT')
B2  <- lmer(blame_rating ~ 1 + ignorance*scenario + (1 | participant), df.exp_long, REML=T)
summary(B2)


###Parwise T test for scenario
install.packages("emmeans")
library(emmeans)
emmeans(B2, list(pairwise ~ scenario), adjust = "tukey")

```



```{r}
## correlations 

# Causal - Knowledge
cor.test(df.exp_long$causal_rating, df.exp_long$know_rating) 
pwr.r.test(n=98,r=.45)

# Blame - Knowledge
cor.test(df.exp_long$blame_rating, df.exp_long$know_rating) 
pwr.r.test(n=98,r=.45)

# Causal - Blame
cor.test(df.exp_long$blame_rating, df.exp_long$causal_rating) 
```

```{r}

##### Correlation Plot Matrix 

library(ggplot2)
install_github("ggobi/ggally")

myTheme <-   theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 18, vjust=.9), 
                   axis.text.x = element_text(color="black", size = 18),
                   axis.text.y = element_text(color="black", size = 18), 
                   strip.text.x = element_text(color="black", size = 18),
                   legend.text = element_text(color="black", size = 18),
                   legend.position = "top",
                   legend.title = element_blank(),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"))


blame_plot<- ggplot(df.exp_long, aes(x=ignorance, y=blame_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(1, 7, by=1))+
  stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha=0.5) +
  stat_summary( fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0.2, dodge.width = 0.90, jitter.width=0.15), alpha = 
  0.08, colour="grey")+
  theme_void()

know_plot<- ggplot(df.exp_long, aes(x=ignorance, y=know_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(1, 7, by=1))+
  stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha=0.5) +
  stat_summary( fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0.2, dodge.width = 0.90, jitter.width=0.15), alpha = 
  0.08, colour="grey")+
  theme_void()

cause_plot<- ggplot(df.exp_long, aes(x=ignorance, y=causal_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(1, 7, by=1))+
  stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha=0.5) +
  stat_summary( fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0.2, dodge.width = 0.90, jitter.width=0.15), alpha = 
  0.08, colour="grey")+
  theme_void()


p_ <- GGally::print_if_interactive

my_colors <- c("self-caused" = "blue", "externally caused" = "green")

corr.plot<- ggpairs(df.exp_long, 
      columns = c("know_rating", "causal_rating", "blame_rating"), 
      ggplot2::aes(colour=ignorance),
      upper = "blank",
      diag = "blank",
      columnLabels = c("Knowledge Rating", "Causal Rating", "Blame Rating"),
      lower= list(continuous=wrap("smooth", alpha = 0.4, size=0.2, position=position_jitter(height=0.2, width=0.2))),
       switch = "both")+
      coord_cartesian(xlim = c(1,7)) +
      coord_cartesian(ylim = c(1,7)) +
      scale_y_continuous(breaks = seq(1, 7, by=1))+
      scale_x_continuous(breaks = seq(1, 7, by=1))+
  theme_bw()+
  theme(           axis.title.x = element_text(color="black", size = 12),
                   axis.title.y = element_text(color="black", size = 12), 
                   axis.text.x = element_text(color="black", size = 12),
                   axis.text.y = element_text(color="black", size = 12),
                   strip.text.x = element_text(color="black", size = 12),
                   strip.text.y = element_text(color="black", size = 12),
                   legend.text = element_text(color="black", size = 12),
                   strip.background = element_rect(fill="white"))


corr.plot[1,1]<-cause_plot
corr.plot[2,2]<-know_plot
corr.plot[3,3]<-blame_plot


p_(corr.plot)

```

```{r}
library(ggplot2)
install_github("ggobi/ggally")

myTheme <-   theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 18, vjust=.9), 
                   axis.text.x = element_text(color="black", size = 18),
                   axis.text.y = element_text(color="black", size = 18), 
                   strip.text.x = element_text(color="black", size = 18),
                   legend.text = element_text(color="black", size = 18),
                   legend.position = "top",
                   legend.title = element_blank(),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"))


blame_plot<- ggplot(df.exp_long, aes(x=ignorance, y=blame_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(1, 7, by=1))+
  stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha=0.5) +
  stat_summary( fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0.2, dodge.width = 0.90, jitter.width=0.15), alpha = 
  0.08, colour="grey")+
  theme_void()

know_plot<- ggplot(df.exp_long, aes(x=ignorance, y=know_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(1, 7, by=1))+
  stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha=0.5) +
  stat_summary( fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0.2, dodge.width = 0.90, jitter.width=0.15), alpha = 
  0.08, colour="grey")+
  theme_void()

cause_plot<- ggplot(df.exp_long, aes(x=ignorance, y=causal_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(1, 7, by=1))+
  stat_summary(fun.y = mean, geom = "bar", position = "dodge", colour = "black", alpha=0.5) +
  stat_summary( fun.data = mean_cl_boot, geom = "errorbar", position = position_dodge(width = 0.90), width = 0.2) +
  geom_jitter(position = position_jitterdodge(jitter.height = 0.2, dodge.width = 0.90, jitter.width=0.15), alpha = 
  0.08, colour="grey")+
  theme_void()


p_ <- GGally::print_if_interactive

my_colors <- c("self-caused" = "blue", "externally caused" = "green")

corr.plot<- ggpairs(df.exp_long, 
      columns = c("know_rating", "causal_rating", "blame_rating"), 
      ggplot2::aes(colour=ignorance),
      upper = "blank",
      diag = "blank",
      columnLabels = c("Knowledge Rating", "Causal Rating", "Blame Rating"),
      lower= list(continuous=wrap("smooth", alpha = 0.4, size=0.2, position=position_jitter(height=0.2, width=0.2))),
       switch = "both")+
      coord_cartesian(xlim = c(1,7)) +
      coord_cartesian(ylim = c(1,7)) +
      scale_y_continuous(breaks = seq(1, 7, by=1))+
      scale_x_continuous(breaks = seq(1, 7, by=1))+
  theme_bw()+
  theme(           axis.title.x = element_text(color="black", size = 12),
                   axis.title.y = element_text(color="black", size = 12), 
                   axis.text.x = element_text(color="black", size = 12),
                   axis.text.y = element_text(color="black", size = 12),
                   strip.text.x = element_text(color="black", size = 12),
                   strip.text.y = element_text(color="black", size = 12),
                   legend.text = element_text(color="black", size = 12),
                   strip.background = element_rect(fill="white"))


corr.plot[1,1]<-cause_plot
corr.plot[2,2]<-know_plot
corr.plot[3,3]<-blame_plot


p_(corr.plot)
```






```{r}

###know rating predicts blame
cor(df.exp_long$blame_rating, df.exp_long$know_rating)  #


Blame_Know <- lm(blame_rating ~ know_rating, df.exp_long)  # build linear regression model on full data
print(Blame_Know)

summary(Blame_Know)

Blame_Know2 <- lm(blame_rating ~ know_rating +ignorance, df.exp_long)
summary(Blame_Know2)

scatter.smooth(x=df.exp_long$know_rating, y=df.exp_long$blame_rating) 


ggplot(df.exp_long, aes(x = know_rating, y = blame_rating, colour = ignorance)) + geom_point()


fig1b <- ggplot(df.exp_long, aes(x= know_rating, y=blame_rating, colour = ignorance)) +
  #geom_errorbarh(aes(xmin=d1Relevance-d1rSE, xmax=d1Relevance+d1rSE), linetype=3) +
  #geom_errorbar(aes(ymin=d1Cause-d1SE, ymax=d1Cause+d1SE), linetype=3) +
  #stat_summary(fun.data = mean,
               #fun.ymin = function(x) mean(x) - sd(x), 
               #fun.ymax = function(x) mean(x) + sd(x), 
               #geom = "pointrange") +
  geom_point(stat = "identity", position = "jitter")+
  #geom_point(aes(colour=scenario, shape=ignorance), position = "jitter",size=rel((6))) +
  #geom_text(aes(label=Agent),stat = "identity",size=rel((4))) +
  stat_smooth(method=lm, formula= y ~ x) +
  #coord_cartesian(ylim=c(.2,1)) +
  theme_bw() +
  ylab("Blame Judgment") +
  xlab("know Judgment") +
  theme(
    plot.background = element_blank()
    ,panel.grid.major = element_blank()
    ,panel.grid.minor = element_blank()
    #,legend.position=c(.85,.15)
    ,legend.title=element_blank()
    ,legend.text=element_text(size=rel(1.25))
    ,axis.text=element_text(size=rel(1.5))
    ,strip.text=element_text(size=rel(1.25))
    ,axis.title.y=element_text(vjust=.9)
    ,axis.ticks = element_blank()
    ,axis.title=element_text(size=rel(1.5))
    ,plot.title = element_text(face="bold",vjust=.75)
  )

fig1b

fig1c <- ggplot(df.exp_long, aes(x= causal_rating, y=blame_rating, colour = ignorance)) +
  #geom_errorbarh(aes(xmin=d1Relevance-d1rSE, xmax=d1Relevance+d1rSE), linetype=3) +
  #geom_errorbar(aes(ymin=d1Cause-d1SE, ymax=d1Cause+d1SE), linetype=3) +
  #stat_summary(fun.data = mean,
               #fun.ymin = function(x) mean(x) - sd(x), 
               #fun.ymax = function(x) mean(x) + sd(x), 
               #geom = "point") +
  geom_point(stat = "identity", position = "jitter")+
  #geom_point(aes(colour=scenario, shape=ignorance), stat = "identity", position = "jitter",size=rel((6))) +
  #geom_text(aes(label=Agent),stat = "identity",size=rel((4))) +
  stat_smooth(method=lm, formula= y ~ x) +
  #coord_cartesian(ylim=c(.2,1)) +
  theme_bw() +
  ylab("Blame Judgment") +
  xlab("Cause Judgment") +
  theme(
    plot.background = element_blank()
    ,panel.grid.major = element_blank()
    ,panel.grid.minor = element_blank()
    #,legend.position=c(.85,.15)
    ,legend.title=element_blank()
    ,legend.text=element_text(size=rel(1.25))
    ,axis.text=element_text(size=rel(1.5))
    ,strip.text=element_text(size=rel(1.25))
    ,axis.title.y=element_text(vjust=.9)
    ,axis.ticks = element_blank()
    ,axis.title=element_text(size=rel(1.5))
    ,plot.title = element_text(face="bold",vjust=.75)
  )

fig1c



```

###### Selection of externally caused ignorance: code category external vs. own action could have been different.


```{r}


#### Analysing Causal etc. Ratings according to Counterfactual Response category


Fig2b2 <- df.exp_long %>% 
  filter(counterfactual=="... self-caused" | counterfactual=="... externally caused") %>% 
  ggplot(aes(x=counterfactual, y=causal_rating, fill=counterfactual)) + 
  coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_jitter(height = 0.1, width = 0.1, alpha =  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  
  scale_fill_manual(values=c("gray42", "gray72"))+
  facet_wrap(~ignorance)+
  labs( y="Causal Rating")+
  theme_bw()+
  myTheme+
  theme(axis.text.x = element_text(angle = 20, hjust = 1, color="black", size = 14))

Fig2b2


Fig2a <- ggplot(df.exp_long, aes(x=scenario, y=causal_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  geom_jitter(position = position_jitterdodge(jitter.height = 0.1, dodge.width = 0.8, jitter.width=0.2), alpha = 
  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  
  scale_fill_manual(values=c("#999999", "#E69F00"), name="blank")+
  labs( y="Causal Rating")+
  theme_bw()+
  myTheme




#######t test

Externally_caused <- df.exp_long %>% 
  filter(counterfactual=="... self-caused" | counterfactual=="... externally caused") %>% 
  filter(ignorance == "externally caused") 

var.test(Externally_caused %>% filter(counterfactual=="... self-caused") %>% pull(causal_rating),
                      Externally_caused %>% filter(counterfactual=="... externally caused") %>% pull(causal_rating))



Externally_caused_t <-
  t.test(Externally_caused %>% filter(counterfactual=="... self-caused") %>% pull(causal_rating),
                      Externally_caused %>% filter(counterfactual=="... externally caused") %>% pull(causal_rating),
                      var.equal = F) %>%
  tidy()





```



```{r}
######3D Scatterplot all data

install.packages("scatterplot3d") # Install
library("scatterplot3d") # load

x<-df.exp_long$causal_rating
y<-df.exp_long$know_rating
z<-df.exp_long$blame_rating
colors <- c("#999999", "#E69F00")
colors <- colors[as.numeric(df.exp_long$ignorance)]



plot<-scatterplot3d(x,y,z, pch = 16, color=colors, grid=T, angle = 30,
              main="3D Scatter Plot",
              xlab = "Causal Rating",
              ylab = "Know Rating",
              zlab = "Blame Rating") 
my.lm <- lm(z ~ x+ y)
plot$plane3d(my.lm)

plot<-scatterplot3d(x,y,z, pch = 20,  angle = 20)

```

```{r}
######3D Scatterplot by condition

x<-df.exp_long$causal_rating[df.exp_long$ignorance=="self-caused"]
y<-df.exp_long$know_rating[df.exp_long$ignorance=="self-caused"]
z<-df.exp_long$blame_rating[df.exp_long$ignorance=="self-caused"]


plot_1<-scatterplot3d(x,y,z, pch = 16, grid=T, angle = 40,
                       main="3D Scatter Plot",
              xlab = "Causal Rating",
              ylab = "Know Rating",
              zlab = "Blame Rating") 
my.lm <- lm(z ~ x+ y)
plot_1$plane3d(my.lm)


x<-df.exp_long$causal_rating[df.exp_long$ignorance=="externally caused"]
y<-df.exp_long$know_rating[df.exp_long$ignorance=="externally caused"]
z<-df.exp_long$blame_rating[df.exp_long$ignorance=="externally caused"]


plot_2<-scatterplot3d(x,y,z, pch = 16, grid=T, angle = 40,
              main="3D Scatter Plot",
              xlab = "Causal Rating",
              ylab = "Know Rating",
              zlab = "Blame Rating") 
my.lm <- lm(z ~ x+ y)
plot_2$plane3d(my.lm)

```


```{r}
library(car)
# 3D plot with the regression plane
x<-df.exp_long$causal_rating
y<-df.exp_long$know_rating
z<-df.exp_long$blame_rating
scatter3d(x = x, y = y, z = z, 
          point.col = "blue", groups = df.exp_long$ignorance, grid = FALSE, fit = "smooth",
          axis.col = c("black", "black", "black"),
          xlab = "Causal Rating", ylab = "Knowledge Rating",
         zlab = "Blame Rating")
```











