---
title: "Epistemic States and Statistical Normality in Causal Judgments"
author: "Lara Kirfel & David Lagnado"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  bookdown::html_document2:
    toc: true
    toc_depth: 4
    theme: cosmo
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")
```

# Install packages

```{r, message=FALSE}
install.packages("pastecs");
install.packages("reshape")
install.packages("lubridate")
install.packages("lsr")
install.packages("janitor")
install.packages("DT")
install.packages("Hmisc")
install.packages("broom")
install.packages("tidyverse")
install.packages("ez")
install.packages("schoRsch")
install.packages("stringr")
```

# Load packages 

```{r, message=FALSE}
library("pastecs")
library("reshape")
library("knitr")
library("lubridate")
library("lsr")
library("janitor") # for cleaning variable names 
library("DT") # for nice tables
library("Hmisc") # for smean function for bootstrapped confidence intervals 
library("broom") # for tidy regression results
library("tidyverse") # for data wrangling, visualization, etc. 
library("ez")
library("schoRsch")
library("lme4")
library("stringr")
library("dplyr")
library("nlme")

```

```{r}
# set ggplot theme 
theme_set(
  theme_classic()
)
```

# Experiment 1:

## Read in Data

```{r}
df.data = read.csv(file = "EpStates_2.csv", stringsAsFactors = F, sep = ",") %>% 
  filter(row_number() > 2) %>% # additional rows in qualtrics csv
  clean_names() %>% 
  filter(distribution_channel != "preview",
         !condition =="", #exclude bot fails,
          progress ==100| progress==99|progress==98)
 
```

## Structure and edit data

```{r}

df.exp = df.data %>% 
  mutate(participant = 1:n()) %>% 
  rename(duration=duration_in_seconds) %>% 
  mutate(duration=as.numeric(duration)) %>% 
  select(h_check_fact_1:b_b_2_1,
         participant,
         order,
         duration,
         condition,
         gender,
         age,
         -starts_with("q")
         ) %>% 
  gather("index", "value", -c(age, gender, participant, condition, duration, order))%>% 
  filter(value != "") %>%
  arrange(index)%>%
  mutate(index = ifelse(str_detect(index,"_c_1"),
                        "cause_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_c_2"),
                        "cause_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_cf_1"),
                        "cf_externally_caused",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_cf_2"),
                        "cf_self_caused",
                        index)) %>% 
  mutate(index = ifelse(str_detect(index,"_k_1"),
                        "could_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_k_2"),
                        "could_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_b_1"),
                        "blame_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"_b_2"),
                        "blame_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"fact_1"),
                        "fact_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"fact_2"),
                        "fact_2",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"know_1"),
                        "know_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"know_2"),
                        "know_2",
                        index)) %>% 
  mutate(index = ifelse(str_detect(index,"mail_1"),
                        "mail_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"mail_2"),
                        "mail_2",
                        index)) %>%
  mutate(index = ifelse(str_detect(index,"read_1"),
                        "read_1",
                        index))%>% 
  mutate(index = ifelse(str_detect(index,"read_2"),
                        "read_2",
                        index)) %>%
  mutate(order = ifelse(order == 1,"dont know first", 
                          ifelse(order == 2, "know first", " ")))%>%
  mutate(scenario = ifelse(condition == 1,"hospital", 
                          ifelse(condition == 2, "garden", 
                          ifelse(condition == 3, "bakery", " "))))%>%
  spread(index, value) %>%
  arrange(participant)

```


```{r}
####Experiment 1: Create filter
df.exp<- df.exp%>%  
  mutate(check_total=if_else(know_1=="2", 1, 0)) %>% 
  mutate(check_total=if_else(know_2 =="1", check_total+1, check_total)) %>% 
  mutate(check_total=if_else(fact_1 =="1", check_total+1, check_total)) %>% 
  mutate(check_total=if_else(fact_2=="1",  check_total+1, check_total))
  
           
#### Set filter
df.exp<-df.exp %>% 
  filter(check_total ==4) ####Set to 4 to change exlusion criterion to "all check questions correct"
```



```{r}

df.exp_cf = df.exp %>% 
  select(participant,
         condition,
         contains("cf"))%>% 
  gather("index", "value", -c(participant, condition))%>% 
  filter(value != "") %>%
  arrange(index)%>%
  mutate(scenario = ifelse(condition == 1,"hospital", 
                          ifelse(condition == 2, "garden", 
                          ifelse(condition == 3, "bakery", " "))))%>%
  spread(index, value) %>%
  arrange(participant)

write.csv(df.exp_cf,'Counterfactuals.csv')
```

##join with counterfactual responses

```{r}
df.counterfactuals<-read.csv("Counterfactuals_analysed.csv") %>% 
  select(participant, code_1, detailed_1, code_2, detailed_2) 
  
df.exp<-df.exp %>% 
inner_join(df.counterfactuals, by="participant") %>% 
filter(code_1 != "0")
```

### Demographics
```{r}
####Experiment 1
###Demographics

df.exp_demo <- df.exp %>% 
  select(age, gender, duration) %>% 
  mutate(age=as.numeric(age)) %>%
  transform(gender= ifelse(gender==1, "Male", #recode numbers into gender categories
                    ifelse(gender==2, "Female",
                    ifelse(gender==3, "Prefer not to say", gender)))) %>% 
  filter(age<100 |age ==" ") %>% #remove outliers (year) or N.A.s
  summarize(n=n(),
             female=sum(gender=="Female"),
             not_say=sum(gender=="Prefer not to say"),
             mean_age = mean(age),
             std_age=sd(age),
             mean_time=mean(duration/60),
             sd_time=sd(duration/60)
            )
```



```{r}

df.exp_long = df.exp %>% 
  select(scenario,
         order,
         participant,
         contains("cause"),
         contains("could"),
         contains("blame"),
         contains("code"),
         contains("detailed"),
         -starts_with("cf"))%>%
  gather(condition, rating, "cause_1":"detailed_2") %>%  
  mutate(ignorance = ifelse(str_detect(condition, "1"),
                        "externally caused", "self-caused")) %>% 
  mutate(condition = ifelse(str_detect(condition, "cause"),"causal_rating", 
                                ifelse(str_detect(condition, "could"), "know_rating", 
                                       ifelse(str_detect(condition, "blame"), "blame_rating",
                                              ifelse(str_detect(condition, "code"), "code_category",
                                                     "code_detailed"))))) %>% 
  spread(condition, rating) %>% 
  mutate(scenario=as.factor(scenario)) %>% 
  mutate(ignorance=as.factor(ignorance)) %>% 
  mutate(causal_rating=as.numeric(causal_rating)) %>% 
  mutate(know_rating=as.numeric(know_rating)) %>% 
  mutate(blame_rating=as.numeric(blame_rating)) 
  

```



```{r}

### Experiment 1
#### Plot Cause  Rating
myTheme <-   theme(axis.title.x  = element_blank(), 
                   axis.title.y = element_text(color="black", size = 18, vjust=.9), 
                   axis.text.x = element_text(color="black", size = 18),
                   axis.text.y = element_text(color="black", size = 18), 
                   strip.text.x = element_text(color="black", size = 18),
                   legend.text = element_text(color="black", size = 18),
                   legend.position = "top",
                   legend.title = element_blank(),
                   panel.grid.major = element_blank(),
                   panel.grid.minor = element_blank(),
                   strip.background = element_rect(fill="white"))
    

## Cause Rating

Fig1a <- ggplot(df.exp_long, aes(x=scenario, y=causal_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  geom_jitter(position = position_jitterdodge(jitter.height = 0.1, dodge.width = 0.8, jitter.width=0.2), alpha = 
  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  

  scale_fill_manual(values=c("#999999", "#E69F00"), name="blank")+
  labs( y="Causal Rating")+
  theme_bw()+
  myTheme

Fig1a

## Could have known Rating

Fig1b <- ggplot(df.exp_long, aes(x=scenario, y=know_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  #geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  geom_jitter(position = position_jitterdodge(jitter.height = 0.1, dodge.width = 0.8, jitter.width=0.2), alpha = 
  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  
  scale_fill_manual(values=c("#999999", "#E69F00"), name="blank")+
  labs( y="Could have known Rating")+
  theme_bw()+
  myTheme

Fig1b

Fig1c <- ggplot(df.exp_long, aes(x=scenario, y=blame_rating, fill=ignorance)) + 
 coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_violin(trim=F, scale = "count", adjust = 3, position=position_dodge(width=0.8), alpha=0.1, color = NA)+
  geom_jitter(position = position_jitterdodge(jitter.height = 0.1, dodge.width = 0.8, jitter.width=0.2), alpha = 
  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  

  scale_fill_manual(values=c("#999999", "#E69F00"), name="blank")+
  labs( y="Blame Rating")+
  theme_bw()+
  myTheme

Fig1c


## Counterfactual Selection

Fig2<-ggplot(df.exp_long, aes(x=code_detailed, group=ignorance))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
  coord_cartesian(ylim = c(0,1)) +
  scale_y_continuous(labels=scales::percent_format(accuracy = 1), breaks = seq(0, 1, by=0.20)) +
  ylab("relative frequencies") +
  facet_wrap(~ignorance)+
  scale_fill_brewer(palette="Greys")+
  theme_bw()+
  myTheme+
  theme(legend.position= "none")

plot(Fig2)

```




```{r}
### Experiment 1
##### Descriptives
### Test Fixed Effects

C1_m1 <- lmer(know_rating ~ knowledge +(1|participant), df.exp_long, REML=F)
C1_m2 <- lmer(know_rating ~ scenario +(1|participant), df.exp_long, REML=F)
C1_m3 <- lmer(know_rating ~ knowledge +scenario + (1|participant), df.exp_long, REML=F)
C1_m4 <- lmer(know_rating ~ knowledge * scenario +(1|participant), df.exp_long, REML=F)

##Effect of Knowledge
anova(C1_m2,C1_m3)

##Effect of Scenario
anova(C1_m1,C1_m3)

##Interaction Knowledge x Scenario
anova(C1_m3,C1_m4)

lmerTest::lmer(know_rating ~ ignorance*scenario + (1 | participant), df.exp_long)%>% summary()

```

```{r}
###Could have known predicts causal


cor(df.exp_long$causal_rating, df.exp_long$know_rating)   

Cause_Know <- lm(causal_rating ~ know_rating, df.exp_long)  
print(Cause_Know)
summary(Cause_Know)


Cause_Know2 <- lm(causal_rating ~ know_rating + ignorance, df.exp_long)
summary(Cause_Know2)

scatter.smooth(x=df.exp_long$know_rating, y=df.exp_long$causal_rating) 


ggplot(df.exp_long, aes(x = know_rating, y = causal_rating, colour = ignorance)) + geom_point()


```
```{r}

####Blame predicts causal

cor(df.exp_long$causal_rating, df.exp_long$blame_rating)  #


Cause_Blame <- lm(causal_rating ~ blame_rating, df.exp_long)  # build linear regression model on full data
print(Cause_Blame)

summary(Cause_Blame)

Cause_Blame2 <- lm(causal_rating ~ blame_rating + ignorance, df.exp_long)
summary(Cause_Blame2)

scatter.smooth(x=df.exp_long$blame_rating, y=df.exp_long$causal_rating) 


ggplot(df.exp_long, aes(x = blame_rating, y = causal_rating, colour = ignorance)) + geom_point()

```

```{r}
cor(df.exp_long$blame_rating, df.exp_long$know_rating)  #


Blame_Know <- lm(blame_rating ~ know_rating, df.exp_long)  # build linear regression model on full data
print(Blame_Know)

summary(Blame_Know)

Blame_Know2 <- lm(blame_rating ~ know_rating +ignorance, df.exp_long)
summary(Blame_Know2)

scatter.smooth(x=df.exp_long$know_rating, y=df.exp_long$blame_rating) 


ggplot(df.exp_long, aes(x = know_rating, y = blame_rating, colour = ignorance)) + geom_point()
```

```{r}
###### Selection of externally caused ignorance: code category external vs. own action could have been different.

Fig3a <- df.exp_long %>% 
  filter(ignorance=="externally caused") %>% 
  filter(code_detailed=="2_3" | code_detailed=="2_4") %>% 
  ggplot(aes(x=code_detailed, y=causal_rating)) + 
  coord_cartesian(ylim = c(1,7)) +
  scale_y_continuous(breaks = seq(0, 7, by=1))+
  geom_violin(trim=F, scale = "count", adjust = 3, width=0.8, alpha=0.1, color = NA)+
  geom_jitter(height = 0.1, width = 0.8, alpha =  0.3, colour = "grey")+
  stat_summary(fun.data = mean_cl_boot, geom = "pointrange", position = position_dodge(width = 0.8), width = 0.2,
  size = 1, shape = 21) +  
  scale_fill_manual(values=c("#999999", "#E69F00"), name="blank")+
  labs( y="Causal Rating")+
  theme_bw()+
  myTheme

Fig3a

```

